version: "3"

networks:
  monitoring:

services:
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring