version: "3"

networks:
  monitoring:

services:
  influxdb:
    build: 
      context: ../influxdb
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - influx:/var/lib/influxdb
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - monitoring
  # flask:
  #   build: 
  #     context: ../server
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - flask:/var/lib/flask
  #   networks:
  #     - monitoring
volumes:
  influx:
  grafana:
  flask: